### PR TITLE
Update .gitattributes

### PR DESCRIPTION
**Pull request by Aliance**

### CODE REVIEW

**Comment by PowerKiKi** [comment]
Please explain in the commit why you are doing this change. And I'd argue that documentation is an essential part of the package and should probably be released together with code source.

Also PHPExcel development for next version has moved under its new name PhpSpreadsheet. So please head over to [PhpSpreadsheet](https://github.com/PHPOffice/PhpSpreadsheet#want-to-contribute) to contribute patches and features. Pull Requests will no longer be accepted for PHPExcel.

**Comment by Aliance** [comment]
Everything's easy – people usually do not need documentation in the `vendor` folder. They use it on package website or other remote places. The same for other files.
This lets decrease the total library size.

Should I need to make pr to PhpSpreadsheet or you are still do not accept this pint of view?

**Comment by PowerKiKi** [comment]
I'm really undecided on this topic. It seems Mark modified this file back and forth too a few times. The [PHP League](https://github.com/thephpleague) and [Zend Framework](https://github.com/zendframework) do it, but [Symphony don't do anymore](https://github.com/symfony/symfony/issues/6605). IMHO docs and tests are very useful to learn how a lib works, and I often have a look at them when developing. But at the same time I see the value of reducing package size for production...

@MarkBaker would you have an opinion on what should and should not be excluded from packages ?

**Comment by Aliance** [comment]
> IMHO docs and tests are very useful to learn how a lib works, and I often have a look at them when developing.

Of course they does, but where are you looking for them? In `vendor` dir or on official site?
Tests needs for developer (someone who clones the repo & makes changes), but not for users, who require your package via composer.

**Comment by PowerKiKi** [comment]
I actually quite often `grep` on my entire project and find matches both in tests and docs which, to me, is very helpful. So yes, I do look in vendor/ for docs and tests. I believe tests are an integral part of documentation to understand internals and how the lib is supposed to be used. So for my own uses I would prefer to always have everything for development. And unfortunately `--prefer-source` make the composer much slower, so I still use `--prefer-sources` even for develop.

That's why I am undecided, and @MarkBaker inputs would be very appreciated.

**Pull request closed without merging**
