### PR TITLE
1.8 secondary axis line chart

### PR DESCRIPTION
**Pull request by Porrapat**
I have made hard code to create easy secondary-Y-axis line chart.

It's now support only line chart on secondary axis only.

Thank you.

### CODE REVIEW

**Comment by PowerKiKi** [comment]
Thank you for your contribution, however PHPExcel development for next version has moved under its new name PhpSpreadsheet. So please consider heading over to [PhpSpreadsheet](https://github.com/PHPOffice/PhpSpreadsheet#want-to-contribute) to contribute patches and features. Pull Requests will no longer be accepted for PHPExcel.

**Comment by Porrapat** [comment]
Thank you for info.

เมื่อ 14 ธ.ค. 2016 19:45 "Adrien Crivelli" <notifications@github.com>
เขียนว่า

**Comment by KishanPatel007** [comment]
Thank you for save my time.

With help of this patch i have created successfully secondary Y axis  But now i have faced one problem is set custom secondary Y axis plot means i want to set custom start point , end point and plot interval for secondary Y axis.

Is it possible in PHPExcel 1.8.1 ?

**Comment by rf1234** [comment]
Hi Porrapat,
thanks a lot for your fix. I adapted it for the current version of PHPSpreadsheet - and it works fine. Unfortunately it is still not integrated into PHPSpreadsheet but I filed a feature request for it. For the time being I am using your solution in hard-coded changes of PHPSpreadsheet.

**Comment by Porrapat** [comment]
@rf1234 Hi! Thank you. It's good to hear! 
Best wish to you all!

**Pull request closed without merging**
