### PR TITLE
Make PHPToExcel use instance of DateTimeInterface rather than DateTime

### PR DESCRIPTION
**Pull request by cvoysey**
This will allow the use of any object implementing `DateTimeInterface`.

https://github.com/PHPOffice/PHPExcel/issues/907

### CODE REVIEW

**Comment by MarkBaker** [comment]
Are there any version issues with this? DateTimeImmutable and DateTimeInterface were only introduced in PHP 5.5

**Comment by cvoysey** [comment]
You're right. How would you typically deal with a version issue like this? In this case it could check for both, which would work, but add code that would be redundant if the project were to ever drop support for older PHP versions.

**Comment by MarkBaker** [comment]
A good question, and one that I don't have an answer for. The 1.8 branch is still targeted at a minimum PHP version of 5.2, and sadly there's still too many people running older versions of PHP like that.

The 1.9 branch is being developed as the more up-to-date version, targeted at PHP 5.4, and using namespacing, etc.... not backward compatible with the 1.8 branch... sadly, changing that from 5.4 to 5.5 might seem like a good idea (still supported versions of PHP), and with all the nice extras like Generators as well; but there's still a sizeable 5.4 userbase that wouldn't be supported. It might be worth raising on https://gitter.im/PHPOffice/PHPExcel to see what consensus there might be for raising the minimum PHP version for the 1.9 branch to 5.5 (the library will also be renamed PHPSpreadsheet in due course), which would then allow your patch to be applied without issue.

**Comment by jurchiks** [comment]
5.3 and 5.4 are both expired, and 5.5 support ends in 1 month (http://php.net/supported-versions.php), you shouldn't support expired versions of PHP. If everyone supports outdated versions, then developers have no incentive to upgrade.

I have long switched to PHP7 for all my projects, but apparently your library is not forward-compatible (https://github.com/PHPOffice/PHPExcel/issues/890). This constructor syntax was introduced in PHP 5.0, so it can easily be upgraded to fix this issue.

**Comment by PowerKiKi** [comment]
This has been done in https://github.com/PHPOffice/PhpSpreadsheet/commit/850594c#diff-495ca961ee5a4a2ab5ae21e6a550a384L229 and more generally in `DateTimeInterface` are introduced in the context of  https://github.com/PHPOffice/PhpSpreadsheet/issues/7

**Pull request closed without merging**
