### PR TITLE
Fixed load HTML with Downlevel Revealed conditional comments

### PR DESCRIPTION
**Pull request by Enyby**
https://css-tricks.com/downlevel-hidden-downlevel-revealed/

```
<![if expression]> 
  HTML 
<![endif]>
```

This comments is not valid for DOM XML parsers. Need convert they to valid form.

```
<!--[if expression]><!-->
  HTML
<!--<![endif]-->
```

### CODE REVIEW

**Comment by PowerKiKi** [comment]
It is not PHPExcel responsability to fix invalid input files

**Comment by Enyby** [comment]
It is not invalid input file. It is valid conditional comment for IE, but for any XML parser it is error.  

See msdn: https://msdn.microsoft.com/en-us/library/ms537512(v=vs.85).aspx
```
downlevel-revealed	<![if expression]> HTML <![endif]>
```

**Comment by PowerKiKi** [comment]
The only supported version of IE by Microsoft [is IE 11](https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support), and conditonnal comments are not supported in IE 11 (since IE 10 as mentioned in [your link](https://msdn.microsoft.com/en-us/library/ms537512(v=vs.85).aspx)). I don't think PHPExcel should support a technology that is obsolete and widely considered bad practice.

**Comment by Enyby** [comment]
Does not matter what version of IE is supported because Excel stay generate code like this:
```
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=100 style='width:75pt'></td>
  <td width=99 style='width:74pt'></td>
  <td width=256 style='width:192pt'></td>
  <td width=63 style='width:47pt'></td>
  <td width=77 style='width:58pt'></td>
  <td width=57 style='width:43pt'></td>
  <td width=256 style='width:192pt'></td>
  <td width=256 style='width:192pt'></td>
  <td width=256 style='width:192pt'></td>
 </tr>
 <![endif]>
```
For HTML table.

PHPExcel must support this formats because Excel make it.

**Pull request closed without merging**
