### PR TITLE
Fixed Undefined offset: 0 errors

### PR DESCRIPTION
**Pull request by nickvellios**
After upgrading from PHP5->PHP7 I also upgraded PHPExcel and received
many “Undefined offset: 0…” errors.  This fixed the problem.

### CODE REVIEW

**Comment by PowerKiKi** [comment]
This have been fixed in https://github.com/PHPOffice/PhpSpreadsheet/commit/5a3e2435c3e069abfb3e5dbcb65bdc63daa4c364 a few weeks ago. Also be careful to use PHPExcel 1.8.1, the latest released version, and not the branch 1.8 which may contains bugs.

And finally PHPExcel development for next version has moved under its new name PhpSpreadsheet. So please consider heading over to [PhpSpreadsheet](https://github.com/PHPOffice/PhpSpreadsheet#want-to-contribute) to contribute patches and features. Pull Requests will no longer be accepted for PHPExcel.

**Comment by nickvellios** [comment]
Thanks.  I appreciate everything you and your team do in the name of opensource, but I am sure I am no the only one suffering from PHPOffice not bringing PHPExcel up to current PHP version compatibility before finishing a stable version of its replacement.

**Comment by PowerKiKi** [comment]
I understand the frustration, but unfortunately we are way under-staffed to support two projects. We are only two guys Mark, the lead who is pretty busy, and myself who arrived only a few weeks ago. Please consider contributing to PhpSpreadsheet if you need to see a faster release.

**Comment by nickvellios** [comment]
I fully understand.  Once it's stable we will be migrating to it and hopefully submitting patches.  Thanks again

**Pull request closed without merging**
