### PR TITLE
Mark all failing unit tests to be skipped

### PR DESCRIPTION
**Pull request by PowerKiKi**
This allow us to start on a clean state, to progressively fix existing
failing tests and add new tests easily. All of that while ensuring that
we don't introduce regressions.

I would recommend merging this as soon as possible to have clean state for further development.

Also, as you can see on my Travis (https://travis-ci.org/PowerKiKi/PHPExcel/builds/15840389) PHP 5.2 is the only version that fails. I would drop support for that version by modyfing `.travis` file. But that may be too drastic and not in line with PHPExcel roadmap ...

### CODE REVIEW

**Comment by PowerKiKi** [comment]
@Progi1984 I see that they are still +100 failing tests on Travis for any given PHP versions. What is the strategy for those ? If they are not skipped, as suggested, it will only add noise for newly implemented tests or newly failing tests. 

I'd go as far as to say that the situation got worse since the time I created this PR. It used to be only ~50 failing tests. And now it is more than twice that.

Obviously the best way to go is to fix all of them at once. But this will take (a lot of) time and meanwhile the situation will degrade even further.

What are you thoughts on that ?

**Comment by Progi1984** [comment]
@PowerKiKi I currently work on branch 1.9 :
* PHPCS tests :
  * 1.8 : 675 Errors
  * 1.9 : 0 Errors
* PHPUnit tests 
  * 1.8 : Tests: 3833, Assertions: 4116, Errors: 1, Failures: 147
  * 1.9 : Tests: 3826, Assertions: 4115, Failures: 107

So If you want to share some pull requests, please do it on 1.9 branch with fix for each failure.
Thanks

**Comment by PowerKiKi** [comment]
This is great news, thanks a lot. I'll spend some time on that 1.9 branch then.

**Comment by Progi1984** [comment]
@PowerKiKi Thanks, we are always open :)

**Pull request closed without merging**
