### PR TITLE
Merge pull request #1 from PHPOffice/develop

### PR DESCRIPTION
**Pull request by CrandellWS**
pull from upstream

### CODE REVIEW

**Comment by MarkBaker** [comment]
Could you perhaps explain what this Pull Request actually does?

**Comment by CrandellWS** [comment]
I am still not very good with git or github and I wanted to get my fork updated...I was trying through the web interface...

**Comment by CrandellWS** [comment]
I wanted to pull your current updates and merge into my fork. I have a project that uses phpexcel that I plan to add this as a sub tree to

**Comment by CrandellWS** [comment]
sorry

**Pull request closed without merging**
