### PR TITLE
Implement actual timezone adjustment into PHPExcel_Shared_Date::PHPToExcel

### PR DESCRIPTION
**Pull request by sim642**
Having encountered issue #38 by accident I took the timezone adjustment code from ExcelToPHP conversion and also applied it here to fix the problem.

### CODE REVIEW

**Comment by sim642** [comment]
Fixed the little `?:` support issue, should be all good now.

**Comment by lode** [comment]
:+1: I was just about to start a PR myself. Would love to see this fixed.

**Comment by svemir** [comment]
Any idea if this is getting rebased and merged eventually?

**Comment by MarkBaker** [comment]
Thanks, now merged into the 1.8 branch

**Comment by sebastienbarre** [comment]
I can not, for the life of me, find this fix in the 1.8 branch. Composer is downloading 1.8.1, and that fix is not there. Really puzzling.

**Comment by PowerKiKi** [comment]
@sebastienbarre, you are looking for https://github.com/PHPOffice/PHPExcel/commit/c4782b660619be139a64d96a545f6a422ca74c20, which is indeed on branch 1.8. But it was never released as part of PHPExcel. You should consider migrating to PhpSpreadsheet.

**Pull request closed without merging**
