### PR TITLE
Fix error on read HTML Document

### PR DESCRIPTION
**Pull request by gustavobeavis**
change instance PHPExecel to Spreadsheet Because is was using the instance of PHPExcel not the Spreadsheet instace, and implemented the explicit use of the DomNode resources

### CODE REVIEW

**Comment by PowerKiKi** [comment]
Development of next version moved to https://github.com/PHPOffice/PhpSpreadsheet. Could you please submit your PR against that new repository's develop branch ?

Sorry for the trouble

**Comment by gustavobeavis** [comment]
No, I don't, I try to use this repository, If there are any problems I make a new contribution.
 tks,

**Comment by MarkBaker** [comment]
I'm going to delete this 1.9 branch.... it was useful for the initial namespacing work, but is causing much more confusion now

**Comment by PowerKiKi** [comment]
@gustavobeavis, thanks for your contribution. This PR has been merged as https://github.com/PHPOffice/PhpSpreadsheet/commit/ba705448464ec38f3527cd3ddc1ace20609b40b3

Please don't use 1.9 branch because it was in the middle of a major refactoring and was utterly broken. Either stay on 1.8, or move on to the future version with its new name and repository at https://github.com/PHPOffice/PhpSpreadsheet.

**Pull request closed without merging**
