### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by glensc**
fill description for recommend tags. the value is not dependency, but informational text:
https://getcomposer.org/doc/04-schema.md#suggest

### CODE REVIEW

**Comment by half2me** [comment]
#814 ext-gd2 will not be resolved. Only ext-gd is supported by composer, with a possible version constraint of ~2

**Comment by glensc** [comment]
indeed, there's no ext-gd2

**Comment by PowerKiKi** [comment]
This has been fixed (probably a long time ago) in https://github.com/PHPOffice/PhpSpreadsheet

**Comment by glensc** [comment]
@PowerKiKi no it is not, there is still `"*"`. i'll submit PR to the new repo and rebase this one against current base. please reopen the PR

**Comment by glensc** [comment]
@PowerKiKi reopen. rebased against `develop` branch

ps: i don't actively use this project anymore

**Pull request closed without merging**
